name: Continuous Integration

on: [push, pull_request]

jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Working..."
      - uses: actions/checkout@v3

      - name: Install dependencies front-end
        run: cd front-end; npm ci

      - name: Install playwright
        run: cd front-end; npx playwright install

      - name: Run tests front-end
        run: cd front-end; npm test

       - name: Run tests back-end
        run: |
          cd back-end/apigateway/code;
          npm install && npm run test;
          cd ../../event/code;
          npm install && npm run test;
          cd ../../user/code;
          npm install && npm run test;
          cd ../../facility/code;
          npm install && npm run test;
          cd ../../sport/code;
          npm install && npm run test

      - name: Run ESLint
        run: cd front-end; npm run code:style; npx eslint --debug .

      - name: Set up JDK 11 for SonarCloud
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze code using SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECTKEY: Lukas117_FitConnect
          SONAR_ORGANIZATION: fitconnect
        with:
          args: -Dsonar.projectKey=${{ env.SONAR_PROJECTKEY }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}